// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCNUEtn4GZ4fZnRmHg0Hdy4wAeKFtv_EZA',
    appId: '1:925264616898:web:51eb3abf78d435b7208a5b',
    messagingSenderId: '925264616898',
    projectId: 'mycampo-6896f',
    authDomain: 'mycampo-6896f.firebaseapp.com',
    storageBucket: 'mycampo-6896f.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxSuHjzTFEIarNuOSbcaCqnxhQ6uceNyw',
    appId: '1:925264616898:android:d215dd200359f7c1208a5b',
    messagingSenderId: '925264616898',
    projectId: 'mycampo-6896f',
    storageBucket: 'mycampo-6896f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCy1Id1B8dmAkx4w3LpFkjiJikrfTSY15I',
    appId: '1:925264616898:ios:e8b5ede42dc4ba81208a5b',
    messagingSenderId: '925264616898',
    projectId: 'mycampo-6896f',
    storageBucket: 'mycampo-6896f.firebasestorage.app',
    iosBundleId: 'it.mycampo.mycampo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCy1Id1B8dmAkx4w3LpFkjiJikrfTSY15I',
    appId: '1:925264616898:ios:e8b5ede42dc4ba81208a5b',
    messagingSenderId: '925264616898',
    projectId: 'mycampo-6896f',
    storageBucket: 'mycampo-6896f.firebasestorage.app',
    iosBundleId: 'it.mycampo.mycampo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCNUEtn4GZ4fZnRmHg0Hdy4wAeKFtv_EZA',
    appId: '1:925264616898:web:bc5e8ddd5763fb62208a5b',
    messagingSenderId: '925264616898',
    projectId: 'mycampo-6896f',
    authDomain: 'mycampo-6896f.firebaseapp.com',
    storageBucket: 'mycampo-6896f.firebasestorage.app',
  );
}
